### PR TITLE
Chrome extension

### PR DESCRIPTION
**Pull request by truprecht**
I added files for a chrome extension which does basically the same as your firefox plugin.

### CODE REVIEW

**Comment by willhelm-mueller** [comment]
Hi Truprecht. 
Thanks for your commit. I already had a short look on it.

**Comment by willhelm-mueller** [comment]
Is your chrome extension also compatible to android devices? Would you like to place your extension on  'chrome store' ?

**Comment by truprecht** [comment]
Afaik, chrome doesn't support extensions on Android. Later I'm going to have a look on how to publish extensions on the chrome store.

**Comment by willhelm-mueller** [comment]
Great!

**Comment by willhelm-mueller** [comment]
I noticed that Chrome for Android does not support extensions :(
[The Chrome FAQ](https://developer.chrome.com/multidevice/faq)

> Does Chrome for Android support apps and extensions?
>     Chrome apps and extensions are currently not supported on Chrome for Android. We have no plans to announce at this time.

**Pull request merged**
